#!/usr/bin/perl -w

use strict;
use FindBin;
use lib $FindBin::Bin;

my $scriptDir = $FindBin::Bin;
my $testDir = $FindBin::Bin . "/../ecmascript/";
my $publishDir = $FindBin::Bin . "/../publish/";

chdir("$testDir");

my @files = `find . -name "*.js"`;

my @templates = ("TEMPLATE.html", "TEMPLATE.xhtml", "TEMPLATE.svg");
my %templateSuffix;
my %templateContents;

for my $templateFile (@templates) {
    {
	local($/);
	open(TEMPLATE, "<${scriptDir}/$templateFile");
	$templateContents{$templateFile} = <TEMPLATE>;
    }
    $templateSuffix{$templateFile} = $templateFile;
    $templateSuffix{$templateFile} =~ s:^[^.]*\.::;
}

print "Generating tests...\n";

sub cleanupPath($) {
    my ($path) = @_;
    $path =~ s:.*/\.\./publish:publish:;
    $path =~ s://:/:g;
    return $path;
}

for my $scriptFile (@files) {
    chomp $scriptFile;
    $scriptFile =~ s:./::;
    
    my $scriptBase = $scriptFile;
    $scriptBase =~ s:^[^/]*/::;
    $scriptBase =~ s:\.js::;

    my $scriptDir = $scriptFile;
    $scriptDir =~ s:^([^/]*/).*$:$1:;
    mkdir "${publishDir}/shared/${scriptDir}";

    my $scriptCopy = "${publishDir}/shared/${scriptDir}${scriptBase}.js";

    open(SCRIPT, "<$scriptFile");
    open(COPY, ">$scriptCopy");

    while (<SCRIPT>) {
	print COPY;
    }
    print COPY "var successfullyParsed = true;";

    close SCRIPT;
    close COPY;

    for my $templateFile (@templates) {
	my $template = $templateContents{$templateFile};
	my $suffix = $templateSuffix{$templateFile};

	my $wrapperBaseDir = $publishDir . $suffix . "/";
	my $wrapperDir = $wrapperBaseDir . $scriptDir;

	mkdir $wrapperBaseDir;
	mkdir $wrapperDir;
	
	my $wrapperFile = "${wrapperDir}/${scriptBase}.${suffix}";
        
	print "    " . cleanupPath(${wrapperFile}) . "\n";
	open WRAPPER, ">$wrapperFile";
	my $output = $template;
	$output =~ s:\@YOUR_JS_FILE_HERE\@:../../shared/${scriptDir}/${scriptBase}.js:;
        print WRAPPER $output;
        close WRAPPER;
    }
}
