=head1 NAME

ReTest - Test framework for Web API specifications

=head1 SYNOPSIS

  retest srcdir publishdir

=head1 DESCRIPTION

=head1 SEE ALSO

=head1 AUTHOR

Maciej Stachowiak, E<lt>mjs@apple.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2006 Apple Computer, Inc.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.6 or,
at your option, any later version of Perl 5 you may have available.

=cut
