# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ReSpec
version:      0.53
version_from: lib/ReSpec.pm
installdirs:  site
requires:
    XML::LibXML:                   
    XML::LibXML::XPathContext:     
    XML::LibXSLT:                  

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
